#!/usr/bin/env bash
# This file transfert a file by scp

IP=$2
USERNAME=$3
PATH_TO_FILE=$1
PATH_TO_SSH_KEY=$4

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME"@"$IP":~/
fi
