#!/usr/bin/env bash
# Install HAproxy and make a simple configuration on two different server

# Installing Haproxy
sudo apt-get install haproxy -y

# Backup the config file
cat /etc/haproxy/haproxy.cfg > /etc/haproxy/haproxy.cfg.backup


echo "
frontend http-frontend
  bind *:80
  mode http
  default_backend http-backend

backend http-backend
   balance roundrobin
   server 429797-web-01 100.26.216.30 check
   server 429797-web-02 100.25.34.201 check
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
