#!/usr/bin/env bash
# It prints a word for infinity

"$(pgrep -f ./100-process_and_pid_file)" > "/var/run/myscript.pid"

trap "echo I hate the kill command; rm /var/run/myscript.pid" TERM
trap "rm /var/run/myscript.pid" QUIT
trap "echo Y U no love me?!" INT
while true; do
	echo "To infinity and beyond"
	sleep 2
done
