#!/usr/bin/env bash
# This script checks files

file="school"

if [ -e "$file" ]
then
	echo "$file file exists"
	state=$(file "$file" | cut -d ':' -f '2-')

	if [ "$state" = " empty" ]; then
		echo "$file file is empty"
	else
		echo "$file file is not empty"
	fi

	if [ -f $file ]; then
		echo "$file is a regular file"
	fi
else
	echo "$file file does not exist"
fi
